from app.schemas.misc import Language, OrgType


org_type_mapping: dict[Language, dict[OrgType, str]] = {
    Language.NLD: {
        OrgType.adviescollege: "Adviescollege",
        OrgType.agentschap: "Agentschap",
        OrgType.brandweer: "Brandweer",
        OrgType.caribisch_openbaar_lichaam: "Caribisch openbaar lichaam",
        OrgType.gemeente: "Gemeente",
        OrgType.grensoverschrijdend_regionaal_samenwerkingsorgaan: (
            "Grensoverschrijdend regionaal samenwerkingsorgaan"
        ),
        OrgType.hoog_college_van_staat: "Hoog College van Staat",
        OrgType.interdepartementale_commissie: "Interdepartementale commissie",
        OrgType.kabinet_van_de_koning: "Kabinet van de Koning",
        OrgType.koepelorganisatie: "Koepelorganisatie",
        OrgType.ministerie: "Ministerie",
        OrgType.openbaar_lichaam_voor_beroep_en_bedrijf: "Openbaar lichaam voor beroep en bedrijf",
        OrgType.organisatie_met_overheidsbemoeienis: "Organisatie met overheidsbemoeienis",
        OrgType.organisatieonderdeel: "Organisatieonderdeel",
        OrgType.politie: "Politie",
        OrgType.provincie: "Provincie",
        OrgType.rechtspraak: "Rechtspraak",
        OrgType.regionaal_samenwerkingsorgaan: "Regionaal samenwerkingsorgaan",
        OrgType.waterschap: "Waterschap",
        OrgType.zelfstandig_bestuursorgaan: "Zelfstandig bestuursorgaan",
        OrgType.overig: "Overig",
    },
    Language.ENG: {
        OrgType.adviescollege: "Advisory board",
        OrgType.agentschap: "Agency",
        OrgType.brandweer: "Fire brigade",
        OrgType.caribisch_openbaar_lichaam: "Caribbean public body",
        OrgType.gemeente: "Municipality",
        OrgType.grensoverschrijdend_regionaal_samenwerkingsorgaan: (
            "Cross-border regional cooperation body"
        ),
        OrgType.hoog_college_van_staat: "High Council of State",
        OrgType.interdepartementale_commissie: "Interdepartmental committee",
        OrgType.kabinet_van_de_koning: "King's Cabinet",
        OrgType.koepelorganisatie: "Umbrella organization",
        OrgType.ministerie: "Ministry",
        OrgType.openbaar_lichaam_voor_beroep_en_bedrijf: "Public body for professions and businesses",
        OrgType.organisatie_met_overheidsbemoeienis: "Organization with government interference",
        OrgType.organisatieonderdeel: "Organizational unit",
        OrgType.politie: "Police",
        OrgType.provincie: "Province",
        OrgType.rechtspraak: "Jurisdiction",
        OrgType.regionaal_samenwerkingsorgaan: "Regional cooperation body",
        OrgType.waterschap: "Water Authority",
        OrgType.zelfstandig_bestuursorgaan: "Independent administrative body",
        OrgType.overig: "Other",
    },
    Language.FRY: {
        OrgType.adviescollege: "Advyskolleezje",
        OrgType.agentschap: "Agentskip",
        OrgType.brandweer: "Brânwacht",
        OrgType.caribisch_openbaar_lichaam: "Karibysk iepen lichem",
        OrgType.gemeente: "Gemeente",
        OrgType.grensoverschrijdend_regionaal_samenwerkingsorgaan: (
            "Grensoerskridend regionaal gearwurkingsorgaan"
        ),
        OrgType.hoog_college_van_staat: "Heech Kolleezje fan Steat",
        OrgType.interdepartementale_commissie: "Ynterdepartemintale kommisje",
        OrgType.kabinet_van_de_koning: "Kabinet fan de Kening",
        OrgType.koepelorganisatie: "Koepelorganisaasje",
        OrgType.ministerie: "Ministerie",
        OrgType.openbaar_lichaam_voor_beroep_en_bedrijf: "Iepen lichem foar berop en bedriuw",
        OrgType.organisatie_met_overheidsbemoeienis: "Organisaasje mei oerheidsoerlis",
        OrgType.organisatieonderdeel: "Organisaasjeûnderdiel",
        OrgType.politie: "Polysje",
        OrgType.provincie: "Provinsje",
        OrgType.rechtspraak: "Rjochtsspraak",
        OrgType.regionaal_samenwerkingsorgaan: "Regionaal gearwurkingsorgaan",
        OrgType.waterschap: "Wetterskip",
        OrgType.zelfstandig_bestuursorgaan: "Selsstannich bestjoersorgaan",
        OrgType.overig: "Oar",
    },
}
