[tool.poetry]
name = "areg-packages"
version = "0.1.0"
description = ""
authors = ["Terry Crapts <terry.crapts@ictu.nl>", "Lars Musters <lars.musters@ictu.nl>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.85.1"}
SQLAlchemy = "^1.4.42"
python-dotenv = "^0.21.0"
alembic = "^1.8.1"
psycopg2-binary = "^2.9.5"
pandas = "^1.5.1"
openpyxl = "^3.0.10"
python-slugify = "^7.0.0"

[tool.poetry.dev-dependencies]
black = {extras = ["jupyter"], version = "^22.10.0"}
flake8 = "^5.0.4"
ipykernel = "^6.16.2"

[tool.poetry.group.dev.dependencies]
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
