interface Config {
  [key: string]: number
}

interface ScoreConfig {
  '0.1': Config
  '0.4': Config
  '1.0': Config
}

const scoreConfig: ScoreConfig = {
  '0.1': {
    name: 8,
    organization: 8,
    department: 8,
    description_short: 8,
    type: 8,
    category: 8,
    website: 2,
    status: 8,
    goal: 8,
    impact: 8,
    proportionality: 8,
    decision_making_process: 8,
    documentation: 2,
    description: 2,
    application_url: 2,
    publiccode: 2,
    mprd: 2,
    source_data: 2,
    methods_and_models: 2,
    monitoring: 2,
    human_intervention: 8,
    risks: 2,
    performance_standard: 2,
    competent_authority: 8,
    lawful_basis: 8,
    iama: 8,
    iama_description: 8,
    dpia: 2,
    dpia_description: 2,
    objection_procedure: 8,
    standard_version: 0,
    uuid: 0,
    url: 2,
    contact_email: 8,
    area: 2,
    lang: 2,
    revision_date: 2,
  },
  '0.4': {
    name: 8,
    organization: 8,
    description_short: 8,
    type: 8,
    category: 8,
    website: 2,
    status: 8,
    begin_date: 8,
    end_date: 0,
    goal: 8,
    proportionality: 8,
    provider: 2,
    lawful_basis: 2,
    lawful_basis_link: 2,
    impacttoetsen: 8,
    iama_description: 2,
    url: 2,
    contact_email: 8,
    lang: 2,
    standard_version: 0,
    uuid: 0,
    source_id: 0,
    tags: 2,
    source_data: 8,
    source_data_link: 0,
    methods_and_models: 2,
    publiccode: 0,
    human_intervention: 8,
    risks: 8,
  },
  '1.0': {
    name: 8,
    description_short: 8,
    organization: 8,
    category: 8,
    status: 8,
    begin_date: 8,
    end_date: 0,
    contact_email: 8,
    website: 2,
    publication_category: 8,
    url: 2,
    goal: 8,
    proportionality: 8,
    human_intervention: 8,
    risks: 8,
    lawful_basis: 2,
    lawful_basis_grouping: 2,
    process_index_url: 2,
    impacttoetsen: 8,
    impacttoetsen_grouping: 2,
    source_data: 8,
    source_data_grouping: 2,
    methods_and_models: 2,
    provider: 8,
    publiccode: 0,
    lang: 2,
    standard_version: 0,
    source_id: 0,
    tags: 2,
  },
}

export default scoreConfig
