excel_column_mapping = {
    "Naam": "name",
    "Organisatie": "organization",
    "Afdeling": "department",
    "Korte omschrijving": "description_short",
    "Type algoritme": "type",
    "Domein": "category",
    "Link naar publiekspagina": "website",
    "Status": "status",
    "Doel": "goal",
    "Impact": "impact",
    "Proportionaliteit": "proportionality",
    "Proces": "decision_making_process",
    "Link naar projectpagina": "documentation",
    "Omschrijving": "description",
    "Link naar ontwikkelaar": "application_url",
    "Link naar broncode": "publiccode",
    "Koppelingen met basisregistraties": "mprd",
    "Databronnen": "source_data",
    "Methoden en modellen": "methods_and_models",
    "Monitoring": "monitoring",
    "Menselijke tussenkomst": "human_intervention",
    "Risico's": "risks",
    "Prestatienormen": "performance_standard",
    "Bevoegde autoriteit": "competent_authority",
    "Wettelijke grondslag": "lawful_basis",
    "Impact Assessment Mensenrechten en Algoritmes (IAMA)": "iama",
    "Omschrijving van de IAMA": "iama_description",
    "Data Protection Impact Assessment (DPIA)": "dpia",
    "Omschrijving van de DPIA": "dpia_description",
    "Bezwaarprocedure": "objection_procedure",
    "Schema": "schema",
    "UUID": "id",
    "URL van de bronregistratie": "url",
    "E-mailadres van de contactpersoon": "contact_email",
    "Geografisch gebied": "area",
    "Taal": "lang",
    "Herzieningsdatum": "revision_date",
}
