# columns will be renamed, but these are needed from the json
df_organisation_columns = ["code","org_id", "type", "show_page"]

df_organisation_details_columns = ["name", "language", "contact_info", "about"]

df_algoritme_columns = ["lars", "create_dt"]

df_algoritme_version_columns = [
    "name",
    "organization",
    "department",
    "description_short",
    "type",
    "category",
    "website",
    "status",
    "goal",
    "impact",
    "proportionality",
    "decision_making_process",
    "documentation",
    "competent_authority",
    "lawful_basis",
    "iama",
    "iama_description",
    "dpia",
    "dpia_description",
    "objection_procedure",
    "standard_version",
    "uuid",
    "url",
    "contact_email",
    "area",
    "lang",
    "revision_date",
    "description",
    "application_url",
    "publiccode",
    "mprd",
    "source_data",
    "methods_and_models",
    "monitoring",
    "human_intervention",
    "risks",
    "performance_standard",
    "create_dt",
    "state",
    "provider",
    "process_index_url",
    "tags",
    "source_id",
    "begin_date",
    "end_date",
    "lawful_basis_link",
    "impacttoetsen",
    "source_data_link",
    "language",
    "publication_category",
    "lawful_basis_grouping",
    "impacttoetsen_grouping",
    "source_data_grouping",
]
